
[functions.getKlaviyoData]
enabled = true
verify_jwt = true
import_map = "./functions/getKlaviyoData/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getKlaviyoData/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getKlaviyoData/*.html" ]

[functions.getShopifyData]
enabled = true
verify_jwt = true
import_map = "./functions/getShopifyData/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getShopifyData/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getShopifyData/*.html" ]

[functions.getKlaviyoFlows]
enabled = true
verify_jwt = true
import_map = "./functions/getKlaviyoFlows/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getKlaviyoFlows/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getKlaviyoFlows/*.html" ]



[functions.convertio-callback]
enabled = true
verify_jwt = true
import_map = "./functions/convertio-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/convertio-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/convertio-callback/*.html" ]

[functions.clickupWebhook]
enabled = true
verify_jwt = true
import_map = "./functions/clickupWebhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clickupWebhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clickupWebhook/*.html" ]

[functions.clickupSync]
enabled = true
verify_jwt = true
import_map = "./functions/clickupSync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/clickupSync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/clickupSync/*.html" ]
