
[functions.getKlaviyoData]
enabled = true
verify_jwt = true
import_map = "./functions/getKlaviyoData/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getKlaviyoData/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getKlaviyoData/*.html" ]

[functions.getShopifyData]
enabled = true
verify_jwt = true
import_map = "./functions/getShopifyData/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/getShopifyData/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/getShopifyData/*.html" ]

[functions.klaviyo_flows]
enabled = true
verify_jwt = true
import_map = "./functions/klaviyo_flows/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/klaviyo_flows/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/klaviyo_flows/*.html" ]

[functions.shopifyBulkWebhookHandler]
enabled = true
verify_jwt = true
import_map = "./functions/shopifyBulkWebhookHandler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/shopifyBulkWebhookHandler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/shopifyBulkWebhookHandler/*.html" ]
